package rules

import com.sample.DroolsTest;
import com.sample.model.QueryDataList;
import com.sample.model.Delo;
import com.sample.model.PodaciODelu;
import com.sample.model.Dokaz;
import com.sample.model.TipTuzioca;
import com.sample.model.Tuzilac;
import com.sample.model.Obelezje;
import com.sample.model.DokazLeaf;
import com.sample.model.DokazRoot;


query Root(String d, int clan, int stav, int tacka)
	DokazRoot(clan, stav, tacka, d;)
end

query Leaf(DokazRoot dokazParent, DokazLeaf opisParent )
	DokazLeaf(dokazParent, opisParent;)
	or
	DokazLeaf(dokazParent, null;)
	or
	DokazLeaf(null, opisParent;)
end

/*
rule "Root dokaz" //Uvidjaj na licu mesta u testu
lock-on-active true
when
	$queryMap: QueryDataList();
	$d: String() from  $queryMap.get("dokaz");
	Root($d, 0, 0, 0;)
then
	System.out.println("Delo zahteva dokaz: " + $d);
end*/

rule "Root dokaz" //Uvidjaj na licu mesta u testu
lock-on-active true
when
	$queryMap: QueryDataList();
	$dr : DokazRoot( );
	$d: String() from  $dr.getOsnovniOpis();
	Root($d, 0, 0, 0;)
then
	System.out.println("Delo zahteva dokaz: " + $d);
end

rule "Leaf dokaz"
lock-on-active true
when
	$root: DokazRoot(  );
	Leaf($root, opisParent;)
then
	//System.out.println("Dokaz \"" +$root.getOsnovniOpis()+"\" zahteva dokaz: ");
	System.out.println("Dokaz \""+$root.getOsnovniOpis()+"\" zahteva dokaz: ");
end



