//created on: 08-Jun-2020
package rules

//list any import classes here.
import com.sample.DroolsTest;
import com.sample.model.Delo;
import com.sample.model.PodaciODelu;
import com.sample.model.Dokaz;
import com.sample.model.TipTuzioca;
import com.sample.model.Tuzilac;
import com.sample.model.Obelezje;


query "OSNOVNI_JAVNI_TUZILAC"
	$delo : Delo ( maxKazna < 10 )
end

query "VISI_JAVNI_TUZILAC"
	$delo : Delo ( maxKazna > 10, naziv != "Ubistvo predstavnika najvisih drzavnih organa" )
end

query "TUZILAC_ZA_MALOLETNIKE"
	$delo : Delo (  )
end

query "TUZILAC_ZA_ORGANIZOVANI_KRIMINAL"
	$delo : Delo ( maxKazna > 10, naziv == "Ubistvo predstavnika najvisih drzavnih organa" )
end



