//created on: 10-May-2020
package rules

//list any import classes here.
import com.sample.DroolsTest;
import com.sample.model.QueryDataList;
import com.sample.model.Delo;
import com.sample.model.PodaciODelu;
import com.sample.model.Dokaz;
import com.sample.model.TipTuzioca;
import com.sample.model.Tuzilac;
import com.sample.model.Obelezje;


//declare any global variables here


rule "114.1.4"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["age2"] == "Vise od 18");
       $s : String() from $queryMap.get("age2");
       $r : String() from $queryMap.get("radnja");
   	   $o : Obelezje(zrtva == $s, radnja.contains($r));
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
    	insert($pd);
end
/*
rule "114.1.9"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["age2"] == "Manje od 18" || this["age2"] == "Bremenita zena");
       $s : String() from $queryMap.get("age2");
   	   $o : Obelezje(zrtva.contains($s), radnja.contains($r.toString()));
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
    	insert($pd);
end
*/


