//created on: 10-May-2020
package rules

//list any import classes here.
import com.sample.DroolsTest;
import com.sample.model.QueryDataList;
import com.sample.model.Delo;
import com.sample.model.PodaciODelu;
import com.sample.model.Dokaz;
import com.sample.model.TipTuzioca;
import com.sample.model.Tuzilac;
import com.sample.model.Obelezje;
import com.sample.model.LinkD;
import com.sample.model.LinkT;


//declare any global variables here


rule "114.1.4 - kradja"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["age2"] == "Vise od 18", this["radnja"] == "Kradja", this["subOdnos"] != "Nehat");
       $s : String() from $queryMap.get("age2");
   	   $o : Obelezje(zrtva == $s, radnja == "Razbojnistvo&Kradja");
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
   	 	System.out.println($s);
    	insert($pd);
end

rule "114.1.4 - razbojnistvo"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["age2"] == "Vise od 18", 
       							 this["radnja"] == "Razbojnistvo", 
       							 this["subOdnos"] != "Nehat");
       $s : String() from $queryMap.get("age2");
   	   $o : Obelezje(zrtva == $s, radnja == "Razbojnistvo&Kradja");
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
   	 	System.out.println($s);
    	insert($pd);
end

rule "114.1.4 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 114, stav == 1, tacka == 4);
		$pd : PodaciODelu(this.compareDelo($d));
		$dk : Dokaz(clan == 0);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);	
end

rule "114.1.9"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["age2"] == "Izmedju 18 i 14" || 
       							 this["age2"] == "Bremenita zena" || 
       							 this["age2"] == "Manje od 14", 
       							 this["subOdnos"] != "Nehat");
       // $s : String() from $queryMap.get("age2");
   	   $o : Obelezje(zrtva == "Izmedju 18 i 14&Manje od 14&Bremenita zena");
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
    	insert($pd);
end

rule "114.1.9 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 114, stav == 1, tacka == 9);
		$pd : PodaciODelu(this.compareDelo($d));
		$dk : Dokaz(clan == 114 && stav == 1 && tacka == 9 || clan == 0);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);	
end





