//created on: May 14, 2020
package rules
//list any import classes here.
import com.sample.DroolsTest;
import com.sample.model.QueryDataList;
import com.sample.model.Delo;
import com.sample.model.PodaciODelu;
import com.sample.model.Dokaz;
import com.sample.model.TipTuzioca;
import com.sample.model.Tuzilac;
import com.sample.model.Obelezje;
//declare any global variables here



rule "114.1.11"
	no-loop true
	when
		$queryMap : QueryDataList(this["age2"]=="Vise od 18");
		$s2 : String() from $queryMap.get("broj");
		$o : Obelezje(zrtva == "Vise od 18", $s2 == "Vise");
		$d : Delo(posebnoObelezje.equals($o));
	then
		PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
   	 	System.out.println("114.1.11");
    	insert($pd);
end

rule "114.1.11 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 114, stav == 1, tacka == 11);
		
		$pd : PodaciODelu(this.compareDelo($d));
		
		$dk : Dokaz(clan == 114, stav == 1, tacka == 11);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);	
end

rule "113"
	no-loop true
	when
		$queryMap : QueryDataList(this["age2"]=="Vise od 18");
		$s2 : String() from $queryMap.get("broj");
		$o : Obelezje(zrtva == "Vise od 18", subjektivanOdnos == "Umisljaj", radnja != "Kradja", $s2 == "1");
		$d : Delo(posebnoObelezje.equals($o));
	then
		PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
   	 	System.out.println("113");
    	insert($pd);
end

rule "113 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 113);
		
		$pd : PodaciODelu(this.compareDelo($d));
		
		$dk : Dokaz(clan == 0);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);	
end

rule "114.1.4 or 114.1.9"
	no-loop true
	when
		$queryMap : QueryDataList(this["age2"]=="Vise od 18");
		$s1 : String() from $queryMap.get("age2");
		$o : Obelezje(zrtva == $s1, radnja =="Kradja");
		$d : Delo(posebnoObelezje.equals($o));
	then
		PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
   	 	System.out.println("114.1.4 or 114.1.9");
    	insert($pd);
end

rule "114.1.4 or 114.1.9 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 114, stav == 1, tacka == 4);
		
		$pd : PodaciODelu(this.compareDelo($d));
		
		$dk : Dokaz(clan == 114, stav == 1, tacka == 4);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);	
end

rule "118"
	lock-on-active true
    when
       $queryMap : QueryDataList(this["subOdnos"] == "Nehat");
       $s : String() from $queryMap.get("subOdnos");
   	   $o : Obelezje(subjektivanOdnos == $s);
       $d : Delo(posebnoObelezje.equals($o));
    then
   	 	PodaciODelu $pd = new PodaciODelu($d);
   	 	System.out.println($pd);
    	insert($pd);	
end



rule "tuzilac maksimalna kazna manja od 10"
	no-loop true
	when
		$d : Delo(maxKazna < 10);
		$pd : PodaciODelu(this.compareDelo($d) && tuzilac == null);
		$t : Tuzilac(tip == TipTuzioca.OSNOVNI_JAVNI_TUZILAC);
	then
		$pd.setTuzilac($t);
		System.out.println($pd);
		update($pd);
		
end


rule "tuzilac maksimalna kazna veca od 10"
	no-loop true
	when
		$d : Delo(maxKazna > 10);
		$pd : PodaciODelu(this.compareDelo($d) && tuzilac == null);
		$t : Tuzilac(tip == TipTuzioca.VISI_JAVNI_TUZILAC);
	then
		$pd.setTuzilac($t);
		System.out.println($pd);
		update($pd);
		
end

rule "118 dokazi"
	no-loop  true
	when
		$d : Delo(clan == 118);
		
		$pd : PodaciODelu(this.compareDelo($d));
		
		$dk : Dokaz(clan == 0);
	then
		$pd.addToList($dk);
		System.out.println($pd);
		update($pd);
		
		
end
